theme: jekyll-theme-hacker

title: "My Portfolio Space"

description: "A collection of infrastructure projects—from mini builds to major cloud and automation solutions—backed by practical troubleshooting and technical blogs."

show_downloads: true

github:
  repository_url: "https://github.com/myPortfolio-23315"
