theme: jekyll-theme-hacker

title: "Pratul Kumar Patel | Infrastructure & Cloud Portfolio"
description: "Infrastructure, VMware, Cloud, Terraform & DevOps Portfolio"

github:
  repository_url: "https://github.com/myPortfolio-23315"
